### PR TITLE
Modify edit.lua run code to display errors/results of execution and handle require.

### LINKED ISSUE #674: Multishell closes tab too early
when I tell the program to get detailed information with the turtle.getItemDetail(1,true) command it crashes with no return or error

### PR DESCRIPTION
**Pull request by Wojbie**
This change in `edit.lua` program code makes it so that if its possible edit will create `.temp` file in directory currently edited file is. This will make require work consistently with how it will work in edited file. If file is in read only location it will be created in root same as it is currently.

Additionally it adds a handler code to code that is run that will display errors and hold tab open until any key is pressed to indicate user seen the results/errors generated by run action.

Touches #552 
Resolves #674 

Note1: I didn't include code to reset palette because it could have distorted results if someone is messing with palette. If they are unable to read error message it is expected they will realize their pallette changes made reading it impossible.
Note2: `]] .. [[` breaking up that literal string at lines 51 and 52 is there to ensure edit is capable to run edit. It is side effect of run handler code that any code that itself contains a level 33 long bracket literal string will not be run properly. But this should be fairly unlikely situation. If anyone got idea for reasonable code that would deal with this issue it would be helpful.

Example:

obraz
obraz

### CODE REVIEW

**Comment by Wojbie** [comment]
Thanks to @Lupus590 for looking over the prototype and commenting on it.

File: src/main/resources/data/computercraft/lua/rom/programs/edit.lua [hunk 1]
```diff
@@ -47,6 +47,31 @@ else
     stringColour = colours.white
 end
 
+local runHeader = [[local current = term.current()
+local ok,err = load([===============]] .. [[==================[]]
+local runHandler = [[]===============]] .. [[==================], "@.temp", nil, _ENV)
```
Comment (SquidDev) [inline src/main/resources/data/computercraft/lua/rom/programs/edit.lua:52]: Instead of doing this horror story, could we do something like the following:

```lua
local runHandler = [[
local current = term.current()
local ok, err = load(%q, %q, nil, _ENV)
...
]]
```


And then:

```lua
local str = runHandler:format(table.concat(tLines, "\n"), "@" .. fs.getName(sPath))
```

Probably also worth dropping the `highlightColour`/`bgColour` - I'd just make those white and black respectively.

File: src/main/resources/data/computercraft/lua/rom/programs/edit.lua [hunk 2]
```diff
@@ -47,6 +47,31 @@ else
...
+if ok then ok,err = pcall(ok,...) end
+term.redirect(current)
+term.setTextColor(%i)
+term.setBackgroundColor(%i)
+term.setCursorBlink(false)
+local _,y = term.getCursorPos()
+local _,h = term.getSize()
+if err then
```
Comment (SquidDev) [inline src/main/resources/data/computercraft/lua/rom/programs/edit.lua:60]:
```suggestion
if not ok then
```

Otherwise this'll trigger if someone returns a value from the program.

File: src/main/resources/data/computercraft/lua/rom/programs/edit.lua [hunk 3]
```diff
@@ -47,6 +47,31 @@ else
     stringColour = colours.white
 end
 
+local runHeader = [[local current = term.current()
+local ok,err = load([===============]] .. [[==================[]]
+local runHandler = [[]===============]] .. [[==================], "@.temp", nil, _ENV)
+if ok then ok,err = pcall(ok,...) end
```
Comment (SquidDev) [inline src/main/resources/data/computercraft/lua/rom/programs/edit.lua:53]: Stupid nitpick, sorry, but can you add spaces after all the commas. It's consistent with the rest of the code - it's just the linter won't pick up on this.

File: src/main/resources/data/computercraft/lua/rom/programs/edit.lua [hunk 4]
```diff
@@ -47,6 +47,31 @@ else
...
+local _,h = term.getSize()
+if err then
+    printError(err)
+end
+if not err and y >= h then
+    term.scroll(1)
+end
+term.setCursorPos(1,h)
+if not err then
+    write("Execution finished. ")
```
Comment (SquidDev) [inline src/main/resources/data/computercraft/lua/rom/programs/edit.lua:68]:
```suggestion
    write("Program finished. ")
```

Up to you - IMO it's a little friendlier?

File: src/main/resources/data/computercraft/lua/rom/programs/edit.lua [hunk 5]
```diff
@@ -101,9 +126,11 @@ local function save(_sPath)
     local function innerSave()
         file, fileerr = fs.open(_sPath, "w")
         if file then
+            if bRun then file.write(runHeader) end
```
Comment (SquidDev) [inline src/main/resources/data/computercraft/lua/rom/programs/edit.lua:129]: Using a boolean here feels a little bit weird. Maybe instead we should accept a callback, and do something like:

```lua
if file then
  write(file)
end
```

Then when calling it do this for the "Save" command:

```lua
save(sPath, function(x)
  for _, sLine in ipairs(tLines) do
    file.write(sLine .. "\n")
  end
end)
```

And this for the "Run" command:

```lua
save(sTempPath, function(file)
  file.write(runHandler:format(table.concat(tLines, "\n"), "@" .. fs.getName(sPath)))
end)

File: src/main/resources/data/computercraft/lua/rom/programs/edit.lua [hunk 6]
```diff
@@ -47,6 +47,31 @@ else
...
+local _,y = term.getCursorPos()
+local _,h = term.getSize()
+if err then
+    printError(err)
+end
+if not err and y >= h then
+    term.scroll(1)
+end
+term.setCursorPos(1,h)
+if not err then
```
Comment (SquidDev) [inline src/main/resources/data/computercraft/lua/rom/programs/edit.lua:67]: Similarly here

```suggestion
if ok then
```

**Review by SquidDev — COMMENTED** [review]
> This change in edit.lua program code makes it so that if its possible edit will create .temp file in directory currently edited file is. [...] If file is in read only location it will be created in root same as it is currently.

Ooooh, that is nice. Thank you!

**Review by SquidDev — CHANGES_REQUESTED** [review]
That was meant to be a "Request changes". Woops.

Anyway, most of these are nitpicks - the string format one is probably the most important, as yikes the current thing is a little hard to read :p.

File: src/main/resources/data/computercraft/lua/rom/programs/edit.lua (hunk 1 above)
Comment (Wojbie) [reply src/main/resources/data/computercraft/lua/rom/programs/edit.lua]: I will admit i completely forgot that `%q` option exists in lua.

**Comment by Wojbie** [comment]
Added changes as requested.
Additionally added code to set correct multishell tittle for the running file and tweaked the name/logic for temp file. It was pointed to me that I should prevent possibility for edit to overwrite someone existing code now that in creates temp files in directories other then root.

File: src/main/resources/data/computercraft/lua/rom/programs/edit.lua [hunk 7]
```diff
@@ -390,8 +418,18 @@ local tMenuFuncs = {
...
     end,
     Run = function()
-        local sTempPath = "/.temp"
-        local ok = save(sTempPath)
+        local sTitle = fs.getName(sPath)
+        if sTitle:sub(-4) == ".lua" then
+            sTitle = sTitle:sub(1, -5)
+        end
+        local sTempPath = bReadOnly and sTitle .. ".temp" or fs.combine(fs.getDir(sPath), sTitle .. ".temp")
+        if fs.exists(sTempPath) then
```
Comment (SquidDev) [inline src/main/resources/data/computercraft/lua/rom/programs/edit.lua:426]: Can we call this `".temp." .. sTitle` instead? Just so the file is hidden.

Alternatively go full `(".temp.%s-%08x"):format(sTitle, math.random(0x7FFFFFFF))`, then then don't worry about overwriting files.

**Review by SquidDev — CHANGES_REQUESTED** [review]

File: src/main/resources/data/computercraft/lua/rom/programs/edit.lua (hunk 7 above)
Comment (Wojbie) [reply src/main/resources/data/computercraft/lua/rom/programs/edit.lua:426]: I don't this there is actually point it going that deep in this case. First filename you suggested will be way more rare then what i used ;p

**Review by SquidDev — APPROVED** [review]

**Comment by SquidDev** [comment]
Thanks!
